import { useEffect,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import api from '../api/axios'
const toDateTime=(s)=>s?s.length===16?`${s}:00`:s:null
export default function AddAttendance(){
 const nav=useNavigate(),[employees,setEmployees]=useState([]),[form,setForm]=useState({employeeId:'',attendanceDate:'',status:'PRESENT',checkIn:'',checkOut:''}),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{api.get('/api/employees').then(r=>setEmployees(r.data)).catch(e=>setError(e.response?.data?.message||'Unable to load employees.'))},[])
 const submit=async(e)=>{e.preventDefault();setError('');if(!form.employeeId||!form.attendanceDate)return setError('Employee and date are required.');if(form.checkIn&&form.checkOut&&form.checkOut<form.checkIn)return setError('Check-out cannot be before check-in.');try{setSaving(true);await api.post('/api/attendance',{employeeId:Number(form.employeeId),attendanceDate:form.attendanceDate,status:form.status,checkIn:toDateTime(form.checkIn),checkOut:toDateTime(form.checkOut)});nav('/attendance')}catch(e){setError(e.response?.data?.message||'Unable to create attendance record.')}finally{setSaving(false)}}
 return <div className="page-container"><div className="page-header"><div><h1>Add Attendance</h1><p>Record an employee attendance entry.</p></div><button className="secondary-button" onClick={()=>nav('/attendance')}>Back</button></div>{error&&<div className="error-banner">{error}</div>}<div className="form-card"><form onSubmit={submit}><div className="form-grid"><div className="form-group"><label>Employee</label><select value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} required><option value="">Select employee</option>{employees.map(x=><option key={x.employeeId} value={x.employeeId}>{x.employeeCode} — {x.firstName} {x.lastName}</option>)}</select></div><div className="form-group"><label>Date</label><input type="date" value={form.attendanceDate} onChange={e=>setForm({...form,attendanceDate:e.target.value})} required/></div><div className="form-group"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>PRESENT</option><option>ABSENT</option><option>HALF_DAY</option><option>LEAVE</option></select></div><div className="form-group"><label>Check In</label><input type="datetime-local" value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/></div><div className="form-group"><label>Check Out</label><input type="datetime-local" value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/></div></div><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>nav('/attendance')}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Saving...':'Record Attendance'}</button></div></form></div></div>
}
