import { useEffect,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import api from '../api/axios'
const local=(v)=>v?v.slice(0,16):''
export default function EditAttendance(){
 const {attendanceId}=useParams(),nav=useNavigate(),[employees,setEmployees]=useState([]),[form,setForm]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{Promise.all([api.get(`/api/attendance/${attendanceId}`),api.get('/api/employees')]).then(([a,e])=>{const r=a.data;setForm({employeeId:r.employeeId||'',attendanceDate:r.attendanceDate||'',status:r.status||'PRESENT',checkIn:local(r.checkIn),checkOut:local(r.checkOut)});setEmployees(e.data)}).catch(e=>setError(e.response?.data?.message||'Unable to load attendance record.'))},[attendanceId])
 if(!form)return <div className="page-container"><p className="loading">{error||'Loading attendance...'}</p></div>
 const submit=async(e)=>{e.preventDefault();if(form.checkIn&&form.checkOut&&form.checkOut<form.checkIn)return setError('Check-out cannot be before check-in.');try{setSaving(true);await api.put(`/api/attendance/${attendanceId}`,{employeeId:Number(form.employeeId),attendanceDate:form.attendanceDate,status:form.status,checkIn:form.checkIn?`${form.checkIn}:00`:null,checkOut:form.checkOut?`${form.checkOut}:00`:null});nav('/attendance')}catch(e){setError(e.response?.data?.message||'Unable to update attendance.')}finally{setSaving(false)}}
 return <div className="page-container"><div className="page-header"><div><h1>Edit Attendance</h1><p>Update attendance record.</p></div><button className="secondary-button" onClick={()=>nav('/attendance')}>Back</button></div>{error&&<div className="error-banner">{error}</div>}<div className="form-card"><form onSubmit={submit}><div className="form-grid"><div className="form-group"><label>Employee</label><select value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} required>{employees.map(x=><option key={x.employeeId} value={x.employeeId}>{x.employeeCode} — {x.firstName} {x.lastName}</option>)}</select></div><div className="form-group"><label>Date</label><input type="date" value={form.attendanceDate} onChange={e=>setForm({...form,attendanceDate:e.target.value})} required/></div><div className="form-group"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>PRESENT</option><option>ABSENT</option><option>HALF_DAY</option><option>LEAVE</option></select></div><div className="form-group"><label>Check In</label><input type="datetime-local" value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/></div><div className="form-group"><label>Check Out</label><input type="datetime-local" value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/></div></div><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>nav('/attendance')}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Saving...':'Save Changes'}</button></div></form></div></div>
}
